apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: creditinstitute
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creditinstitute
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100 # % of "request"s limit defined in the deployment
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 100 # % of "request"s limit defined in the deployment
