- job_name: 'spring-actuator'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 10s
  static_configs:
  - targets: ['creditinstitute-cs', 'cart-cs', 'inventory-cs', 'orchestrator-cs', 'order', 'payment', 'ui-cs', 'uibackend-cs']
