
prometheus:
  prometheusSpec:
    probeNamespaceSelector: {}
    probeSelector: {}
    additionalScrapeConfigsSecret:
        enabled: true
        name: additional-config
        key: prometheus-additional-scrape-config.yaml

prometheusSpec:
  probeNamespaceSelector: {}
  probeSelector: {}

probeNamespaceSelector: {}
probeSelector: {}

alertmanager:

  enabled: true

  config:

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'

    receivers:
      - name: 'null'
      - name: 'web.hook'
        webhook_configs:
        - url: 'http://sla-manager-service.default.svc.cluster.local'



        
