global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:8082/api/v2/alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']


#config:
#  global: {}
#    # slack_api_url: ''
#
#  templates:
#    - '/etc/alertmanager/*.tmpl'
#
#  receivers:
#    - name: default-receiver
#      # slack_configs:
#      #  - channel: '@you'
#      #    send_resolved: true
