# Set env variables temporarily in current session
$Env:T2_COMMON_VERSION="1.3-SNAPSHOT"
$Env:T2_TRAM_VERSION="0.34.0.RELEASE"
$Env:T2_TRAM_PARTICIPANT_VERSION="0.23.0.RELEASE"
$Env:T2_JAEGER_VERSION="3.3.1"
$Env:T2_RESILIENCE4J_VERSION="2.2.0"
$Env:T2_JACOCO_VERSION="0.8.11"
$Env:T2_MICROMETER_VERSION="1.12.1"
$Env:T2_SPRINGDOC_VERSION="2.3.0"
$Env:T2_APACHE_HTTPCLIENT_VERSION="4.5.14"

$Env:T2_JAEGER_ENABLED="false"
