#! /bin/bash
# Set env variables temporarily in current session
export T2_COMMON_VERSION=1.3-SNAPSHOT
export T2_TRAM_VERSION=0.34.0.RELEASE
export T2_TRAM_PARTICIPANT_VERSION=0.23.0.RELEASE
export T2_JAEGER_VERSION=3.3.1
export T2_RESILIENCE4J_VERSION=2.1.0
export T2_JACOCO_VERSION=0.8.11
export T2_MICROMETER_VERSION=1.11.4
export T2_SPRINGDOC_VERSION=2.2.0
export T2_APACHE_HTTPCLIENT_VERSION=4.5.14

export T2_JAEGER_ENABLED=false
