
prometheus:
  prometheusSpec:
    probeNamespaceSelector: {}
    probeSelector: {}
    # Additional Scrape Config Secret
    additionalScrapeConfigs:
      - job_name: 'spring-actuator'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 10s
        static_configs:
        - targets: ['creditinstitute-cs', 'cart-cs', 'inventory-cs', 'orchestrator-cs', 'order', 'payment', 'ui-cs', 'uibackend-cs']

prometheusSpec:
  probeNamespaceSelector: {}
  probeSelector: {}

probeNamespaceSelector: {}
probeSelector: {}

alertmanager:

  enabled: true

  config:

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'

    receivers:
      - name: 'null'
      - name: 'web.hook'
        webhook_configs:
        - url: 'http://sla-manager-service.default.svc.cluster.local'



        
