apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: stiesssh/payment:v0.1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: zookeeper:2181
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres/eventuate
            - name: SPRING_DATASOURCE_USERNAME
              value: eventuate
            - name: T2_PAYMENT_PROVIDER_DUMMY_URL
              value: http://e2etest/fakepay
            - name: T2_PAYMENT_PROVIDER_TIMEOUT
              value: "5"
            - name: JAEGER_SERVICE_NAME
              value: payment
            - name: JAEGER_ENABLE
              value: "TRUE"
            - name: JAEGER_HOST
              value: jaeger-agent
      restartPolicy: Always
