---
name: T2-Microservices (Minimal Scenario with JMeter, simulate compute intensive task)
author: David Kopp
description: Scenario to simulate a compute intensive task. Each time an order is confirmed, a compute intensive task is executed that takes a few seconds (depending on the configuration and machine).

compose-file: !include microservices-compose.yml

services:
  computation-simulator:
    image: t2project/computation-simulator:main
    expose:
      - "8080"
    environment:
      T2_COMPUTATION_SIMULATOR_PI_TOTAL_POINTS: 50000000 # requires a few seconds
    healthcheck:
      test: curl -m 5 -f -s http://localhost:8080/actuator/health/readiness | grep UP || exit 1
      start_period: "30s"
      start_interval: "1s"
      interval: "1h"
  orchestrator:
    log-stdout: true
    read-notes-stdout: true
    read-sci-stdout: true
    environment:
      T2_GMT_LOGGING_ENABLED: true # SCI note get logged by orchestrator after Saga completed
  uibackend:
    environment:
      T2_COMPUTATION_SIMULATOR_ENABLED: "TRUE"
      T2_COMPUTATION_SIMULATOR_URL: http://computation-simulator:8080/
    depends_on:
      cart:
        condition: service_started
      inventory:
        condition: service_started
      orchestrator:
        condition: service_started
      computation-simulator:
        condition: service_started

sci:
  R_d: order
  # One order consists of three sequential requests: get inventory, add product to cart, confirm order

flow:
  - name: single user orders one product
    container: jmeter
    commands:
      - type: console
        command: jmeter -Jhostname=uibackend -Jport=8080 -JnumExecutions=1 -JnumUser=1 -JrampUp=0 -JnumProducts=1 -JthinkTimeMin=0 -JthinkTimeAdditionalRange=0 -JpauseAfterExecution=0 -JloggingEnabled=true -JloggingSCIEnabled=false -n -t /tmp/repo/loadprofiles/t2-project-flexible.jmx
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: false
