---
name: T2-Modulith (Minimal Scenario with JMeter, simulate compute intensive task)
author: David Kopp
description: Scenario to simulate a compute intensive task. Each time an order is confirmed, a compute intensive task is executed that takes a few seconds (depending on the configuration and machine).

compose-file: !include monolith-compose.yml

services:
  computation-simulator:
    image: t2project/computation-simulator:main
    expose:
      - "8080"
    environment:
      T2_COMPUTATION_SIMULATOR_PI_TOTAL_POINTS: 50000000 # requires a few seconds
    setup-commands:
      - sleep 15 # wait some time to ensure that the computation-simulator is ready
  postgres:
    setup-commands:
      - sleep 5 # wait some time to ensure that the database is ready
  backend:
    setup-commands:
      - sleep 10 # wait some time to ensure that the backend is ready
    environment:
      T2_COMPUTATION_SIMULATOR_ENABLED: "TRUE"
      T2_COMPUTATION_SIMULATOR_URL: http://computation-simulator:8080/

sci:
  R_d: order
  # One order consists of three sequential requests: get inventory, add product to cart, confirm order

flow:
  - name: single user orders one product
    container: jmeter
    commands:
      - type: console
        command: jmeter -Jhostname=backend -Jport=8080 -JnumExecutions=1 -JnumUser=1 -JrampUp=0 -JnumProducts=1 -JthinkTimeMin=0 -JthinkTimeAdditionalRange=0 -JloggingEnabled=true -JloggingSCIEnabled=true -n -t /tmp/repo/t2-project-flexible.jmx
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
