services:

  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    networks:
      - t2-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: "5s"
      timeout: "5s"
      retries: 10
      start_period: "10s"
  
  mongo:
    image: bitnami/mongodb:7.0
    expose:
      - "27017"
    networks:
      - t2-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: "5s"
      timeout: "5s"
      retries: 10
      start_period: "10s"

  backend:
    image: t2project/modulith:main
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      MONGO_HOST: mongo
      POSTGRES_HOST: postgres
      SPRING_PROFILES_ACTIVE: simple
    networks:
      - t2-network
    healthcheck:
      test: curl -m 5 -f -s http://localhost:8080/actuator/health/readiness | grep UP || exit 1
      interval: "5s"
      timeout: "5s"
      retries: 10
      start_period: "10s"

  jmeter:
    image: t2project/jmeter:5.6.2
    environment:
      JVM_XMN: 150 # maximum nursery size
      JVM_XMS: 250 # initial heap size
      JVM_XMX: 1000 # maximum heap size
    networks:
      - t2-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  t2-network:
