apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: T2_COMPUTATION_SIMULATOR_ENABLED
              value: "TRUE"
            - name: T2_COMPUTATION_SIMULATOR_PI_TOTAL_POINTS
              value: "10000000" # requires 500-1000 ms
