prometheus:
  prometheusSpec:
    probeNamespaceSelector: {}
    probeSelector: {}

    scrapeInterval: 5s # scrape interval of monitored targets, default: 30s
    evaluationInterval: 5s # evaluation interval for rules (used for new time series and alerting), default: 30s

    # Additional Scrape Config Secret
    additionalScrapeConfigs:
      - job_name: 'spring-actuator'
        scrape_interval: 5s # default: 30s
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          # Relabel to scrape only services that have
          # the annotation `prometheus.io/scrape: "true"`.
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Relabel to scrape only services that are part of the t2-microservices / t2-monolith
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_part_of]
            action: keep
            regex: t2.+
        # static_configs:
        # - targets: ['creditinstitute.default', 'cart.default', 'inventory.default', 'orchestrator.default', 'order.default', 'payment.default', 'ui.default', 'uibackend.default']

alertmanager:
  enabled: false
  config:
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'

    # receivers:
    #   - name: 'null'
    #   - name: 'web.hook'
    #     webhook_configs:
    #     - url: 'http://sla-manager-service.default.svc.cluster.local'

## Monitors ConfigMap and Secret changes and notifies the target process.
## Ref: https://github.com/jimmidyson/configmap-reload
configmapReload:
  prometheus:
    enabled: true
    name: configmap-reload
    image:
      repository: jimmidyson/configmap-reload
      tag: v0.12.0
      # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
      digest: ""
      pullPolicy: IfNotPresent
