groups:
- name: provider-alerts
  rules:

  - alert: provider_avail_avg_slo
    expr: 'avg_over_time(probe_success[1m]) <= 0.9'
    labels:
      severity: error
    annotations:
      summary: "Bad Availability on {{ $labels.instance }} /  {{ $labels.target }}"
      value: "{{ $value }}"
      solomonId: "5e25b2a4-6b5d-4317-95e7-6a8245226e64"

  - alert: provider_respT_avg_slo
    expr: 'avg_over_time(http_server_requests_seconds[10s]) >= 10'
    for: 10s
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      value: "{{ $value }}"
      solomonId: "67cc8ce2-3f78-4122-ad36-d9640efdde40"
