apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdcservice
  name: cdcservice
spec:
  ports:
    - name: "8099"
      port: 8099
      targetPort: 8080
  selector:
    app: cdcservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdcservice
  name: cdcservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdcservice
  template:
    metadata:
      labels:
        app: cdcservice
    spec:
      containers:
        - env:
          - name: JAVA_OPTS
            value: -Xmx64m
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: kafka:29092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: kafka-zookeeper:2181

          - name: EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE
            value: eventuate-tram
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE1_READER
            value: reader1
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA
            value: t2_orchestrator

          - name: EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE
            value: eventuate-tram
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE2_READER
            value: reader2
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE2_EVENTUATEDATABASESCHEMA
            value: t2_inventory_service

          - name: EVENTUATE_CDC_READER_READER1_TYPE
            value: postgres-wal
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEURL
            value: jdbc:postgresql://postgres-orchestrator/eventuate
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME
            value: eventuate
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD
            value: eventuate
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME
            value: org.postgresql.Driver
          - name: EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH
            value: /eventuate/cdc/leader/orchestrator
          - name: EVENTUATE_CDC_READER_READER1_OUTBOXID
            value: 1
          - name: EVENTUATE_CDC_READER_READER1_POSTGRESWALINTERVALINMILLISECONDS
            value: 10 # default: 10
          - name: EVENTUATE_CDC_READER_READER1_POSTGRESREPLICATIONSTATUSINTERVALINMILLISECONDS
            value: 1000 # default: 1000

          - name: EVENTUATE_CDC_READER_READER2_TYPE
            value: postgres-wal
          - name: EVENTUATE_CDC_READER_READER2_DATASOURCEURL
            value: jdbc:postgresql://postgres-inventory/inventory
          - name: EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME
            value: inventory
          - name: EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD
            value: inventory
          - name: EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME
            value: org.postgresql.Driver
          - name: EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH
            value: /eventuate/cdc/leader/inventory_service
          - name: EVENTUATE_CDC_READER_READER2_OUTBOXID
            value: 2
          - name: EVENTUATE_CDC_READER_READER2_POSTGRESWALINTERVALINMILLISECONDS
            value: 10 # default: 10
          - name: EVENTUATE_CDC_READER_READER2_POSTGRESREPLICATIONSTATUSINTERVALINMILLISECONDS
            value: 1000 # default: 1000

          image: eventuateio/eventuate-cdc-service:0.16.0.RELEASE
          name: cdcservice
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
      restartPolicy: Always
