apiVersion: v1
kind: Service # headless
metadata:
  labels:
    app: postgres-orchestrator
  name: postgres-orchestrator 
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-orchestrator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres-orchestrator
  name: postgres-orchestrator
spec:
  serviceName: postgres-orchestrator 
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orchestrator
  template:
    metadata:
      labels:
        app: postgres-orchestrator
    spec:
      containers:
        - name: postgres
          image: eventuateio/eventuate-tram-sagas-postgres:0.23.0.RELEASE
          env:
            - name: POSTGRES_DB
              value: eventuate
            - name: POSTGRES_PASSWORD
              value: eventuate
            - name: POSTGRES_USER
              value: eventuate
            - name: USE_DB_ID
              value: "true"
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: datadir
            mountPath: /var/lib/postgresql/data
            subPath: postgres 
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
