apiVersion: v1
kind: Service # headless
metadata:
  labels:
    app: postgres-inventory
  name: postgres-inventory
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-inventory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres-inventory
  name: postgres-inventory
spec:
  serviceName: postgres-inventory 
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres
          image: postgres:14.11
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_PASSWORD
              value: inventory
            - name: POSTGRES_USER
              value: inventory
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: datadir
            mountPath: /var/lib/postgresql/data
            subPath: postgres 
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
