apiVersion: v1
kind: Service # headless
metadata:
  labels:
    app.kubernetes.io/name: eventuate-tram-sagas-postgres
    app.kubernetes.io/instance: postgres-inventory
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 0.23.0.RELEASE
    app.kubernetes.io/part-of: t2project
  name: postgres-inventory
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app.kubernetes.io/instance: postgres-inventory
    app.kubernetes.io/part-of: t2project
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: eventuate-tram-sagas-postgres
    app.kubernetes.io/instance: postgres-inventory
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 0.23.0.RELEASE
    app.kubernetes.io/part-of: t2project
  name: postgres-inventory
spec:
  serviceName: postgres-inventory
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres-inventory
      app.kubernetes.io/part-of: t2project
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventuate-tram-sagas-postgres
        app.kubernetes.io/instance: postgres-inventory
        app.kubernetes.io/component: database
        app.kubernetes.io/version: 0.23.0.RELEASE
        app.kubernetes.io/part-of: t2project
    spec:
      containers:
        - name: postgres
          image: eventuateio/eventuate-tram-sagas-postgres:0.23.0.RELEASE
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_PASSWORD
              value: inventory
            - name: POSTGRES_USER
              value: inventory
            - name: USE_DB_ID
              value: "true"
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: datadir
            mountPath: /var/lib/postgresql/data
            subPath: postgres
          - name: postgres-config
            mountPath: /etc/postgresql/postgresql.conf
            subPath: postgresql.conf
            readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always
      volumes:
      - name: postgres-config
        configMap:
          name: postgres-config
          items:
            - key: postgresql.conf
              path: postgresql.conf
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
