apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-modulith
  name: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: backend
    app.kubernetes.io/part-of: t2-modulith
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-modulith
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: backend
      app.kubernetes.io/part-of: t2-modulith
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-modulith
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_HOST
              value: mongo-mongodb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: T2_CART_TTL
              value: "0"
            - name: T2_CART_TASKRATE
              value: "0"
            - name: T2_INVENTORY_SIZE
              value: "25"
            - name: T2_INVENTORY_TASKRATE
              value: "0"
            - name: T2_INVENTORY_TTL
              value: "0"
            - name: T2_PAYMENT_PROVIDER_ENABLED
              value: "FALSE"
            - name: T2_PAYMENT_PROVIDER_DUMMY_URL
              value: http://creditinstitute/pay
            - name: T2_PAYMENT_PROVIDER_TIMEOUT
              value: "5"
            - name: T2_COMPUTATION_SIMULATOR_ENABLED
              value: "FALSE"
            - name: T2_COMPUTATION_SIMULATOR_PI_TOTAL_POINTS
              value: "1000000000"
          image: t2project/modulith:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 250Mi
      restartPolicy: Always
