apiVersion: v1
kind: Service
metadata:
  name: creditinstitute
  labels:
    app.kubernetes.io/name: creditinstitute
    app.kubernetes.io/instance: creditinstitute
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-modulith
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/instance: creditinstitute
    app.kubernetes.io/part-of: t2-modulith
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditinstitute
  labels:
    app.kubernetes.io/name: creditinstitute
    app.kubernetes.io/instance: creditinstitute
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-modulith
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: creditinstitute
      app.kubernetes.io/part-of: t2-modulith
  template:
    metadata:
      labels:
        app.kubernetes.io/name: creditinstitute
        app.kubernetes.io/instance: creditinstitute
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-modulith
    spec:
      containers:
        - name: creditinstitute
          imagePullPolicy: Always
          env:
            - name: T2_JAEGER_ENABLED
              value: "FALSE"
            - name: T2_JAEGER_HOST
              value: simplest-agent #todo
          image: t2project/creditinstitute:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
      restartPolicy: Always
