apiVersion: v1
kind: Service # headless
metadata:
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 12.16-bullseye
    app.kubernetes.io/part-of: t2-modulith
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/part-of: t2-modulith
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 12.16-bullseye
    app.kubernetes.io/part-of: t2-modulith
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/part-of: t2-modulith
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres
        app.kubernetes.io/component: database
        app.kubernetes.io/version: 12.16-bullseye
        app.kubernetes.io/part-of: t2-modulith
    spec:
      containers:
        - name: postgres
          image: postgres:12.16-bullseye # same version than eventuate postgres image: https://github.com/eventuate-foundation/eventuate-common/blob/master/postgres/Dockerfile
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          args:
            - -c
            - max_connections=1000 # default: 100
            - -c
            - shared_buffers=256MB # default: 128MB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            # limits:
            #   cpu: 500m
            #   memory: 500Mi
            requests:
              cpu: 150m
              memory: 150Mi
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
