apiVersion: v1
kind: Service
metadata:
  name: computation-simulator
  labels:
    app.kubernetes.io/name: computation-simulator
    app.kubernetes.io/instance: computation-simulator
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: computation-simulator
    app.kubernetes.io/part-of: t2-microservices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: computation-simulator
  labels:
    app.kubernetes.io/name: computation-simulator
    app.kubernetes.io/instance: computation-simulator
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: computation-simulator
      app.kubernetes.io/part-of: t2-microservices
  template:
    metadata:
      labels:
        app.kubernetes.io/name: computation-simulator
        app.kubernetes.io/instance: computation-simulator
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-microservices
    spec:
      containers:
        - name: computation-simulator
          imagePullPolicy: Always
          env:
            - name: T2_COMPUTATION_SIMULATOR_PI_TOTAL_POINTS
              value: "100000000"
            - name: T2_JAEGER_ENABLED
              value: "FALSE"
            - name: T2_JAEGER_HOST
              value: simplest-agent #todo
          image: t2project/computation-simulator:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
