apiVersion: apps/v1
kind: Deployment
metadata:
  name: uibackend
spec:
  template:
    spec:
      containers:
        - name: uibackend
          env:
            - name: T2_COMPUTATION_SIMULATOR_ENABLED
              value: "TRUE"
            - name: T2_COMPUTATION_SIMULATOR_URL
              value: http://computation-simulator/compute
