apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: t2project-eks-basic-2
  region: eu-north-1
  version: "1.28"

# At least 6 vCPUs are required
nodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge # m5.2xlarge: 8 vCPU, 32 GB RAM
    desiredCapacity: 1
  # - name: ng-1
  #   instanceType: m5.large # m5.large: 2 vCPU, 8 GB RAM
  #   desiredCapacity: 1
  # - name: ng-2
  #   instanceType: m5.large # m5.large: 2 vCPU, 8 GB RAM
  #   desiredCapacity: 1
  # - name: ng-3
  #   instanceType: m5.large # m5.large: 2 vCPU, 8 GB RAM
  #   desiredCapacity: 1

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  - name: amazon-cloudwatch-observability
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
