apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  annotations:
    # This annotation is optional.
    # If specified, then this prometheus server is used,
    # instead of the prometheus server specified as the CLI argument `--prometheus-server`.
    # metric-config.<metricType>.<metricName>.<collectorType>/<configKey>
    metric-config.external.latency.prometheus/query: |
      sum(rate(http_server_requests_seconds_sum{application="cart"}[1m]))/sum(rate(http_server_requests_seconds_count{application="cart"}[1m]))
    metric-config.latency.prometheus/interval: "15s" # optional
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
