apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: t2project-eks-basic-2
  region: eu-north-1
  version: "1.28"

# A capacity for a minimum of ~60 pods is required
nodeGroups:
  - name: ng-1
    instanceType: m5.large # m5.large: 2 vCPU, 8 GB RAM
    desiredCapacity: 4

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  - name: amazon-cloudwatch-observability
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
    - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
