apiVersion: v1
kind: Service
metadata:
  labels:
    app: creditinstitute-cs
  name: creditinstitute-cs
spec:
  selector:
    app: creditinstitute
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: creditinstitute-solomon
  labels:
    app: creditinstitute-cs
    monitoring: "true"
    solomonTarget: "true"
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: /metrics
  #   prometheus.io/port: "5000"
spec:
  selector:
    app: creditinstitute
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: creditinstitute
  name: creditinstitute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditinstitute
  template:
    metadata:
      labels:
        app: creditinstitute
    spec:
      containers:
        - name: creditinstitute
          imagePullPolicy: Always
          image: t2project/creditinstitute:main
          ports:
            - containerPort: 8080
      restartPolicy: Always
