apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          imagePullPolicy: Always
          env:
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: kafka-zookeeper:2181
            - name: MONGO_HOST
              value: mongo-order-mongodb
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-orchestrator/eventuate
            - name: SPRING_DATASOURCE_USERNAME
              value: eventuate
            - name: JAEGER_SERVICE_NAME
              value: order
            - name: JAEGER_ENABLE
              value: "TRUE"
            - name: JAEGER_HOST
              value: simplest-agent #todo
          image: t2project/order:main
          ports:
            - containerPort: 8080
      restartPolicy: Always
