apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui-cs
  name: ui-cs
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          imagePullPolicy: Always
          env:
            - name: T2_UIBACKEND_URL
              value: http://uibackend-cs/
          image: t2project/ui:main
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
      restartPolicy: Always
