apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: creditinstitute
  labels:
    t2-scenario: standard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creditinstitute
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # % of the specified resource "requests" in the deployment
