apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../k8s/t2-microservices/autoscaling/
patches:
  - target:
      kind: HorizontalPodAutoscaler
    path: update_hpa.yaml
