apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: any # is not used
spec:
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # % of the specified resource "requests" in the deployment
