apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  template:
    spec:
      containers:
        - name: inventory
          env:
            - name: T2_INVENTORY_SIZE
              value: "1000"
