apiVersion: v1
kind: Service
metadata:
  name: e2etest
  labels:
    app.kubernetes.io/name: e2etest
    app.kubernetes.io/instance: e2etest
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: e2etest
    app.kubernetes.io/part-of: t2-microservices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2etest
  labels:
    app.kubernetes.io/name: e2etest
    app.kubernetes.io/instance: e2etest
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/part-of: t2-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2etest
      app.kubernetes.io/part-of: t2-microservices
  template:
    metadata:
      labels:
        app.kubernetes.io/name: e2etest
        app.kubernetes.io/instance: e2etest
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.3"
        app.kubernetes.io/part-of: t2-microservices
    spec:
      containers:
        - name: e2etest
          image: t2project/e2etest:main
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_SAGA_URL
              value: jdbc:postgresql://postgres-orchestrator/eventuate
            - name: SPRING_DATASOURCE_SAGA_USERNAME
              value: eventuate
            - name: SPRING_DATASOURCE_SAGA_PASSWORD
              value: eventuate
            - name: SPRING_DATASOURCE_SAGA_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_INVENTORY_URL
              value: jdbc:postgresql://postgres-inventory/inventory
            - name: SPRING_DATASOURCE_INVENTORY_USERNAME
              value: inventory
            - name: SPRING_DATASOURCE_INVENTORY_PASSWORD
              value: inventory
            - name: SPRING_DATASOURCE_INVENTORY_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: kafka-zookeeper:2181
            - name: MONGO_HOST # Order MongoDB
              value: mongo-order-mongodb
            - name: T2_ORCHESTRATOR_URL
              value: http://orchestrator/order
            - name: T2_JAEGER_ENABLED
              value: "FALSE"
            - name: T2_JAEGER_HOST
              value: simplest-agent #todo
      restartPolicy: Always
