apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
resources:
  - ./e2etest.yaml
patchesStrategicMerge:
  - delete_creditinstitute.yaml
  - update_payment.yaml
  - update_uibackend.yaml
