apiVersion: apps/v1
kind: Deployment
metadata:
  name: uibackend
spec:
  template:
    spec:
      containers:
        - name: uibackend
          env:
            - name: T2_ORCHESTRATOR_URL
              value: http://e2etest/test
